[package]
name = "aash-simulator"
version = "0.1.0"
edition = "2024"
author = "notpunchnox"
default-run = "main"

[dependencies]
kiss3d = "0.37.0"
rand = "0.9.2"

[lib]
name = "aash_simulator"
path = "src/lib.rs"